### ISSUE TITLE
Uneindeutige Bezeichnungen im Eigenschaften-Fenster

### ISSUE THREAD

**Issue by pascalzurek** [TIK-NFL/ilias-oc-plugin#10]
Zwei Checkboxen:
- "Download" -> was soll das heißen? "Aufzeichnungen zum Download
  freischalten"?
  "Online" -> "Objekt sichtbar für Teilnehmer"?

**Comment by pascalseeland** [comment]
Download kann man umbennen. Dann ist es sicherlich eindeutiger.

Online ist ein ILIAS Standardfeld, was es in allen Einstellung gibt und daher so bleiben sollte
