### ISSUE TITLE
MIMETYPE bei Audio

### ISSUE THREAD

**Issue by pascalzurek** [TIK-NFL/ilias-oc-plugin#13]
Habe eine mp2 hochgeladen und da erscheint als mimetype "Video/mpeg",
das müsste "Audio/mpeg" sein?

**Comment by bogenschlag** [comment]
(Warum) soll(te) Audio vom OC-Plugin überhaupt unterstützt werden? (Es gibt ja in ILIAS auch noch den Mediacast …)

**Comment by pascalzurek** [comment]
Ja, das finde ich auch eigentlich kontraintuitiv, aber Fakt ist, dass man da momentan fast alles hochladen kann und er schluckts. Das ist vielleicht nicht ganz sinnvoll.

**Comment by bogenschlag** [comment]
Gut, Wunsch ist ganz klar: Für den OC-Upload beschränken wir uns auf Video-Material. Es sei denn natürlich, es gibt ein valides Szenario für Audio-only …! (Kann ja sein – aber ich komme gerade nicht drauf.)

**Comment by pascalzurek** [comment]
Ah, siehe anderer Thread :) Aber full ack.
