### ISSUE TITLE
Formatierungsprobleme

### ISSUE THREAD

**Issue by pascalzurek** [TIK-NFL/ilias-oc-plugin#15]
Bitte mehr Platz nach rechts zwischen dem Verarbeitungsfortschrittsbalken (bei "Aufzeichnungen, welche vom Server verarbeitet werden") und dem Job Name.

Auf der "Aufzeichnungen verwalten"-Seite ist außerdem alles sehr gedrängt untereinander. Ein bis zwei Leerzeilen zwischen den einzelnen Tabellen (Fertige/Verarbeitete/Schneiden/Hochladen/Geplante) wären schön, oder hbars.
Man kriegt sonst - gerade wenn noch alles leer ist - die Überschriften nicht so richtig mit.

**Comment by bogenschlag** [comment]
Evtl. sollten wir mal überlegen, ob wir innerhalb des Reiters _Aufzeichnungen Verwalten_ in 3 Unterreiter ausdifferenzieren:
- »Fertige Aufzeichnungen«
- »Aufzeichnungen bearbeiten«
- »Hochladen«

Oder so. Erst mal  nur ein Idee.

**Comment by pascalseeland** [comment]
Hört sich gut an. Gibt es den in ILIAS etwas, wo man so eine weitere Ebene mit Reitern hat. Weil wenn wir das auf der aktuellen Seite machen würde wäre das ja in dem Reiter "Aufzeichnungen verwalten" landen. Oder würdest du neben "Aufzeichnungen verwalten" zwei weiter Reiter zu machen.

**Comment by bogenschlag** [comment]
Dafür findet man Beispiele an zahlreichen Stellen in ILIAS:

![2016-06-07 at 10 37](https://cloud.githubusercontent.com/assets/5374341/15851165/ef4330c4-2c9b-11e6-9240-9f9588114351.png)

![2016-06-07 at 10 38](https://cloud.githubusercontent.com/assets/5374341/15851183/03c481f6-2c9c-11e6-9c11-d5efb78ff182.png)

![2016-06-07 at 10 39](https://cloud.githubusercontent.com/assets/5374341/15851242/35e135b2-2c9c-11e6-9f44-06aa76199eca.png)

**Comment by bogenschlag** [comment]
Schon in Slack angemerkt, aber zu Doku-Zwecken einfach hier noch mal:
- Evtl. würde ich _Aufzeichnungen hochladen_ und ​_Geplante Aufzeichnungen_​ einfach noch vertauschen – letzteres ist ja im Moment erstmal eigentlich der »Default-Fall«.
- Und vielleicht sollte es auch »_Eigene_ Aufzeichnungen hochladen« heißen, um den relativen »Sonderfall«-Charakter deutlicher zu machen.

**Comment by bogenschlag** [comment]
(Ansonsten super jetzt!)
