### ISSUE TITLE
Uploadsicherheit

### ISSUE THREAD

**Issue by pascalzurek** [TIK-NFL/ilias-oc-plugin#16]
Ich habe NUR eine MP2 hochgeladen, und dann will - aus verständlichen Gründen - der Trim
Editor nicht tun. Entweder, der muss auch audio only schneiden können,
oder es darf nicht gehen, dass man eine Audiodatei alleine hochlädt.

Habe ihn auch mal mit ner mpegts beschickt; die mimetype-Klammern
bleiben dann leer (obwohl das ja eigentlich nicht so sein sollte?) und
da geht der upload dann nicht.

**Comment by bogenschlag** [comment]
Ich habe mit Pascal ohnehin schon besprochen, dass man den Trim-Editor (bei selbst hochgeladenem Material) ganz umgehen können sollte. Ich würde bei selbst hochgeladenen Sachen zu 99,8% davon ausgehen, dass die schon geschnitten sind.

Aber noch mal: Woher kommt hier auf einmal eigentlich das Audio-only-Szenario? 😳😏

**Comment by pascalzurek** [comment]
Ich hatte das tatsächlich aus Versehen und gar nicht absichtlich getan, weil ich nämlich einen Upload in zwei Dateien hatte (eine MP2 und eine MKV, in der nur das Video war). Das geht halt nicht, musste ich feststellen, und ist auch okay (gehen wir mal davon aus, dass die meisten Menschen Audio und Video in derselben Datei haben). Aber dann darf man eben kein Audio alleine hochladen dürfen.

**Comment by bogenschlag** [comment]
Ah, verstehe! 😌

**Comment by Legion2** [comment]
Jetzt ist es nur noch möglich mp4 und webm hochzuladen.
