### ISSUE TITLE
Mexican jumping job name length

### ISSUE THREAD

**Issue by bogenschlag** [TIK-NFL/ilias-oc-plugin#18]
Abhängig von der jeweils aktuellen Länge des »Job Name« (nebenbei besser vielleicht »Verarbeitungsstatus«) springen die Spalten _Verarbeitungsfortschritt_ und _Job Name_ in der Breite lustig hin und her – das sollte vielleicht nicht so …? 😌

![2016-05-20 at 10 42](https://cloud.githubusercontent.com/assets/5374341/15422287/14128332-1e78-11e6-9834-6f8593c390d4.png)

**Comment by pascalseeland** [comment]
Keine Ahnung ob das mit dem ILIAS-Table-Classes irgendwie geht. Mein Vorschlag wäre, die Jobname-Info einfach in ein Overlay zu packen. Man könnte das Overlay dann auch gleich noch mit I18n versehen und dabei dann die OC-Jobnames mit passenden Text übersetzen. Was ich in diesem Zug auch noch mit einnbauen würde wäre dann eine Info ob der Job eventuell länger dauert (Trim/Convert/Segment) dort en hinweiß anzuzeigen. Sollten wir mal mit Theo reden, ob ihm was einfällt.
