### ISSUE TITLE
"Convert uploaded file into a defined format": Dauer schätzen?

### ISSUE THREAD

**Issue by bogenschlag** [TIK-NFL/ilias-oc-plugin#19]
Wäre es möglich, für "Convert uploaded file into a defined format" die voraussichtliche Dauer anzugeben? Das scheint ja ein länglicher(er) Schritt zu sein und das wäre an der Stelle bestimmt gutes Feedback.

Nur mal eine Idee für die Zukunft.

**Comment by pascalseeland** [comment]
Ne, kann man nicht. Ausser mit ziemlich viel Aufwand, da die Prozesse ja auch irgend einem Worker laufen und es auch dort derzeit nichts gibt mit dem man so was eventuell aus ffmpeg wieder auslesen kann. Bestenfalls kann man dort an dem Text was machen, so dass die leute wissen das dieser Schritt dauert.

**Comment by bogenschlag** [comment]
Ok—was nicht geht, geht nicht.
