### ISSUE TITLE
Update-Funktion

### ISSUE THREAD

**Issue by pascalseeland** [TIK-NFL/ilias-oc-plugin#25]
It should be possible to update a series information in opencast without it being overwritten the next time something is changed on the ILIAS side, since ILIAS currently just overwrites the series information in opencast. Updating requires that the file gets first read from opencast before writing it back.

**Comment by Legion2** [comment]
When should the update happen, every time the Opencast object is loaded in Ilias or only when `editProperties` is called?

**Comment by Legion2** [comment]
currently overwritten information:
- all

currently hard coded:
- title (ILIAS-$obj_id:$refId:$title)
- publisher (University of Stuttgart, Germany)
- format (video/mp4)

possible to update in ilias:
- references (lectureid)
- description
