### ISSUE TITLE
Missing feedback on upload page 

### ISSUE THREAD

**Issue by pascalseeland** [TIK-NFL/ilias-oc-plugin#29]
- In case a file is select and not all mandatory fields are filed out, no button will be clickable. There should be some kind of feedback that a field is missing.
- The mandatory fields need to be more obvious.
- The input method should be aligned to the ILIAS mediacast object

**Comment by pascalgrube** [comment]
There is also a need making the manditory fields more obious

**Comment by Legion2** [comment]
We can use the [FileUpload Service](https://github.com/ILIAS-eLearning/ILIAS/blob/release_5-3/src/FileUpload/README.md) instead of our own implementation. This includes [Dropzone](https://ilias.de/test53/goto.php?target=stys_21_DropzoneFileStandardStandard_default_delos&client_id=test53) with support for restricted file types #13 #16.

**Comment by pascalseeland** [comment]
I don't think we can use the FileUpload Service, as it will store the file on the disk. Our service does take the individual chunks it receives from the client and sends it directly onward to the opencast server.

**Comment by Legion2** [comment]
We cloud first upload the complete file to ilias and then send it to opencast and remove it from the disk. I see no advantage of sending separate chunks.

**Comment by pascalseeland** [comment]
There are several issues that are avoided by sending the file as chunks:
- We sending the complete file to ILIAS, we are restricted by the maximum upload file size of ILIAS. At our installation this would be 2GB file limit, which might not be enough depending on the video being uploaded.
- It avoids a lot of disk IO which could cause issues on the ILIAS side, as the file needs to be written and read afterwards.
- I keeps the interface responsive. If the file would be stored in ILIAS, ILIAS would have to upload the file to opencast. During this time, no interaction can be made with ILIAS. Maybe this could be done in a background task, but they did not exist when the plugin was first created and I don't know if they are usable from a plugin.

**Comment by Legion2** [comment]
As discussed this week, we will accept the upload limit. To upload a file to Opencast, the file is first uploaded to Ilias with the Ilias upload service and then uploaded via BackgroundTask or Cron plugin to the Opencast API.
