### ISSUE TITLE
missing hint for naming the pluginfolder

### ISSUE THREAD

**Issue by utesche** [TIK-NFL/ilias-oc-plugin#38]
Please add a hint to README.md that the pluginfolder *MUST* be named  'Matterhorn'...

**Comment by bogenschlag** [comment]
Maybe it is time to change that to _Opencast_ anyway?

**Comment by pascalseeland** [comment]
Changing is difficult, as it is part of the URLs. But putting a hint in the Readme will help for sure

**Comment by bogenschlag** [comment]
True for existing installations, but maybe we could and should change it for new ones? (Leave it as is if more than 10 minutes work!)
