### ISSUE TITLE
UI: Number indicator in tabs

### ISSUE THREAD

**Issue by pascalzurek** [TIK-NFL/ilias-oc-plugin#40]
As many new users do not get the fact that they have to cut the recordings, it would be preferable to have a number indicating uncut recordings in the headline of the tab (like bold printed numbers in any mail client marking unread mails in the folder). This would guide users there.

**Comment by bogenschlag** [comment]
Additionally I still think it would be a good idea to incorporate an *I don’t want to cut anything, just render it automagically* option in the OC ILIAS object settings. (Or do we already have that? In that case, sorry. 😉)

**Comment by pascalseeland** [comment]
We don't have that, but its an entirely different issue. I create issue #41 to track this feature, as it will take time to implement and probably require some work on the opencast side. The number feature is a ui fix, where all information is provided by the backend,.

**Comment by Legion2** [comment]
@pascalzurek Something like this? ![image](https://user-images.githubusercontent.com/12752323/37583881-99b211da-2b53-11e8-9323-13592c752c77.png)
UI Number indicator in the subtabs.

**Comment by bogenschlag** [comment]
Looks like a pragmatic solution.

`0` does not need to be bold IMHO.

**Comment by Legion2** [comment]
in the trim editor the number indicators are not displayed
