### ISSUE TITLE
SerienId in Info Tab

### ISSUE THREAD

**Issue by Legion2** [TIK-NFL/ilias-oc-plugin#59]
Die Serien Id soll im Info Tab im Abschnitt "Opencast Information" angezeigt werden.
Dafür soll die Funktion `addInfoItems` benutzt werden.

**Comment by Legion2** [comment]
@pascalseeland soll die SeriesId mit oder ohne Prefix angezeigt werden? (ilias_xmh_2648263 oder 2648263)

**Comment by pascalzurek** [comment]
Bitte mit Prefix!

**Comment by Legion2** [comment]
sollen nur Kurs admins die SeriesId sehen können? oder ist das nicht schlimm wenn die jeder sehen kann?
