### ISSUE TITLE
The unit tests on the master branch fail

### ISSUE THREAD

**Issue by Legion2** [TIK-NFL/ilias-oc-plugin#82]
[![CI](https://github.com/TIK-NFL/ilias-oc-plugin/workflows/CI/badge.svg)](https://github.com/TIK-NFL/ilias-oc-plugin/actions?query=workflow%3ACI)
The unit tests should be fixed and used to test the code.

**Comment by pascalseeland** [comment]
fixed in https://github.com/TIK-NFL/ilias-oc-plugin/commit/4ce1ca78b2eff353c69c031b929ebe6b39199989
